import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ executablePath: process.env.PQC_CHROMIUM || undefined, headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', error => errors.push(String(error)));
await page.goto('http://127.0.0.1:4173');
await page.getByText('Source hash matches', { exact: false }).first().waitFor();
await page.locator('#plan-status').waitFor();
await page.locator('#plan-scratch').selectOption('0');
assert.match(await page.locator('#plan-status').innerText(), /scratch_limit/);
await page.locator('#plan-basemul').selectOption('directeager');
assert.match(await page.locator('#plan-status').innerText(), /legal/);
await page.locator('#plan-forward').selectOption('fuse2');
await page.locator('#plan-next').click();
assert.match(await page.locator('#plan-event').innerText(), /Fused group/);
await page.locator('#step').click();
assert.match(await page.locator('#edge-label').innerText(), /PRODUCT/);
await page.locator('#rs1').fill('1e9');
await page.locator('#arithmetic.error').waitFor();
await page.locator('#rs1').fill('-32768');
await page.waitForFunction(() => document.querySelector('#arithmetic').textContent.includes('residue'));
assert.equal(await page.locator('#eligibility').innerText(), 'No eligible custom implementation');
await page.locator('#lut').fill('13');
await page.locator('#loss').fill('3');
await page.waitForFunction(() => document.querySelector('#eligibility').textContent.includes('Eligible under selected'));
await page.locator('#original').click();
await page.locator('#variant').selectOption('fsri_combinational');
await page.waitForFunction(() => document.querySelector('#latency').textContent.includes('First ready: snapshot 0'));
await page.locator('#operation').selectOption('keygen');
assert.match(await page.locator('#result-rows').innerText(), /missing/);
await page.locator('#mode').selectOption('frequency');
assert.match(await page.locator('#mode-note').innerText(), /Modeled estimate/);
await page.locator('#operation').selectOption('total');
await page.locator('#experiments h2').waitFor();
assert.match(await page.locator('#experiments').innerText(), /8.91%/);
await page.locator('#variant').selectOption('fsri_sliced');
await page.waitForFunction(() => document.querySelector('#arithmetic').textContent.includes('low_half'));
await page.locator('#run').click();
await page.locator('#cancel').click();
await page.locator('#step').click();
assert.match(await page.locator('#edge-label').innerText(), /PRODUCT/);
await page.route('**/evidence/fsri_sliced.sv', route => route.fulfill({ status: 200, body: 'stale source' }));
await page.locator('#preset').selectOption('fsri_sliced-1');
await page.waitForFunction(() => document.querySelector('#trace-status').textContent.includes('STALE EVIDENCE'));
await page.unroute('**/evidence/fsri_sliced.sv');
await page.locator('#preset').selectOption('fsri_sliced-0');
await page.waitForFunction(() => document.querySelector('#trace-status').textContent.includes('Source hash matches'));

await page.screenshot({ path: '../build/workbench/desktop.png', fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
await page.screenshot({ path: '../build/workbench/mobile.png', fullPage: true });
assert.deepEqual(errors, []);
await page.route('**/evidence/catalog.json', route => route.fulfill({ status: 404, body: '{}' }));
await page.reload();
await page.getByRole('heading', { name: 'Evidence unavailable' }).waitFor();
await browser.close();
console.log('browser walkthrough passed desktop mobile operands playback budget missing data and frequency model');
