import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ executablePath: process.env.PQC_CHROMIUM || undefined, headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', error => errors.push(String(error)));
await page.goto('http://127.0.0.1:4173');
await page.getByText('Source hash matches', { exact: false }).first().waitFor();
await page.locator('#step').click();
assert.match(await page.locator('#edge-label').innerText(), /PRODUCT/);
await page.locator('#rs1').fill('1e9');
await page.locator('#arithmetic.error').waitFor();
await page.locator('#rs1').fill('-32768');
await page.waitForFunction(() => document.querySelector('#arithmetic').textContent.includes('residue'));
assert.equal(await page.locator('#eligibility').innerText(), 'No eligible custom implementation');
await page.locator('#lut').fill('13');
await page.locator('#loss').fill('3');
await page.waitForFunction(() => document.querySelector('#eligibility').textContent.includes('Eligible under selected'));
await page.locator('#original').click();
await page.locator('#variant').selectOption('fsri_combinational');
await page.waitForFunction(() => document.querySelector('#latency').textContent.includes('First ready: snapshot 0'));
await page.locator('#operation').selectOption('keygen');
assert.match(await page.locator('#result-rows').innerText(), /missing/);
await page.locator('#mode').selectOption('frequency');
assert.match(await page.locator('#mode-note').innerText(), /Modeled estimate/);
await page.locator('#operation').selectOption('total');
await page.screenshot({ path: '../build/workbench/desktop.png', fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
await page.screenshot({ path: '../build/workbench/mobile.png', fullPage: true });
assert.deepEqual(errors, []);
await browser.close();
console.log('browser walkthrough passed desktop mobile operands playback budget missing data and frequency model');
